version: '3'

services:
  app:
    # build: .
    build: 
      dockerfile: Dockerfile.prod
    image: prawee/strapi:1.4.0
    container_name: my-app
    ports:
      - 8080:1337
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      # - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - APP_KEYS=${APP_KEYS}
      - JWT_SECRET=${JWT_SECRET}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    container_name: my-db
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
  caddy:
    image: caddy:latest
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
